name: fengchao
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  flutter_i18n: ^0.7.0
  flutter_spinkit: ^4.0.0
  dio: ^3.0.3
  photo_manager: ^0.4.1
  bot_toast: ^2.0.0+2
  flutter_rating_bar: ^3.0.0
  flutter_swiper: ^1.1.6
  pull_to_refresh: ^1.5.6
  flutter_staggered_grid_view: ^0.3.0
  # city_pickers: ^0.1.27
  lpinyin: ^1.0.7
  meta: ^1.1.7
  shared_preferences: ^0.5.4+1
  qr_flutter: ^3.0.1
  flutter_qr_reader: 1.0.2
  permission_handler: '^3.0.0'
  provider: ^3.1.0+1
  wave: ^0.0.8
  # flutter_bloc: ^1.0.0
  # equatable: ^0.6.0
  keyboard_visibility: ^0.5.6
  flutter_baidu_map: ^0.0.5
  # 图片处理
  image: ^2.1.4
  path_provider: ^1.4.0
  extended_image: 0.6.5
  extended_image_library: 0.1.8
  isolate: ^2.0.2 
  photo_view: ^0.7.0
  image_gallery_saver: ^1.2.2
  encrypt: ^3.3.1
  flare_flutter: ^1.7.1
  open_file: ^2.1.1
  fluwx: ^1.1.3
  tobias: ^1.2.0
  url_launcher: ^5.2.7
  web_socket_channel: ^1.1.0
  mask_text_input_formatter: ^1.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
  assets:
    - assets/images/
    - assets/animation/
    - assets/images/gallery/sunnies.png
    - assets/images/gallery/table.png
    - assets/images/gallery/earrings.png
    - assets/images/gallery/hat.png
    - assets/i18n/
  fonts:
    - family: iconfont
      fonts:
        - asset: fonts/iconfont.ttf